[package]
name = "tzparse"
version = "0.1.0"
authors = ["Nicolas BAUW <nbauw@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
tzfile = { git = "https://github.com/nicolasbauw/rs-tzfile.git", tag="v0.1.0" }
