[package]
name = "tzparse"
version = "0.3.1"
authors = ["Nicolas BAUW <nbauw@hotmail.com>"]
edition = "2018"
license = "GPL-3.0"
repository = "https://github.com/nicolasbauw/rs-tzparse"
description = "A high-level library to read timezone information files (TZfiles)."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
libtzfile = "0.4.0"